import { readFileSync, statSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

export const PROJECTS_DIR = join(homedir(), '.claude', 'projects');

export interface Session {
  /** session UUID — the value passed to `claude --resume` */
  id: string;
  /** absolute path to the .jsonl transcript */
  path: string;
  /** working directory the session ran in (where we relaunch) */
  cwd: string;
  /** human-readable title (aiTitle, or a prompt fallback) */
  title: string;
  /** last user prompt, for the detail pane */
  lastPrompt: string;
  gitBranch: string;
  permissionMode: string;
  messageCount: number;
  /** file mtime in ms — drives freshness + "running" detection */
  mtimeMs: number;
  /** ms timestamp of the last *conversational* record (user/assistant turn).
   *  Unlike file mtime this ignores metadata-only writes — `--resume` on open,
   *  permission-mode / ai-title / last-prompt sidecar records — so it reflects
   *  "last time I messaged or claude was active", which is the sidebar order. */
  lastActivityMs: number;
  /** ms timestamp of the last message *I* sent — a real human prompt, not a
   *  tool result, meta record or sub-agent turn. This is the "I touched this"
   *  signal the sidebar orders on; see attentionMs. 0 if I never typed. */
  lastUserMs: number;
  /** ms timestamp of the FIRST conversational record — effectively when the
   *  session was created. 0 if the transcript has no timestamped turns. */
  firstActivityMs: number;
  /** type of the final transcript record */
  lastType: string;
  /** uuid of the first conversational record. `claude --resume` (since ~mid
   *  2026) FORKS: it copies the history into a NEW session file (new id) and
   *  continues there, leaving the old file behind. The copied records keep
   *  their uuids, so this value survives the fork and identifies the logical
   *  conversation across all its files. '' if no uuid'd turns yet. */
  firstUuid: string;
  /** true when the last *conversational* record is a user turn with no
   *  assistant reply yet — i.e. a turn is in flight. Used (gated on recency) to
   *  tell a session that's actively generating from a dormant one. */
  awaitingReply: boolean;
  /** true for a resume stub: `claude --resume` writes the inherited
   *  ai-title/agent-name into the fork's NEW file immediately, so quitting
   *  without sending a message leaves a transcript with a title but zero
   *  turns. It has no firstUuid to collapse on, so it would render as a
   *  duplicate of its parent. (A genuinely new session can't look like this —
   *  titles are only generated after the first exchange.) */
  isStub: boolean;
}

interface CacheEntry {
  mtimeMs: number;
  session: Session;
}

// Parsed metadata is cached by mtime so the 2s poll only re-reads changed files.
const cache = new Map<string, CacheEntry>();

function truncate(s: string, n: number): string {
  const clean = (s || '').replace(/\s+/g, ' ').trim();
  return clean.length > n ? clean.slice(0, n - 1) + '…' : clean;
}

// Claude Code injects meta/command messages as "user" records; these make poor
// titles, so skip them when falling back to the first prompt.
function isJunkText(s: string): boolean {
  const t = s.trim();
  if (!t) return true;
  if (t.startsWith('<')) return true; // <command-name>, <local-command-stdout>, etc.
  if (/^Caveat:/i.test(t)) return true;
  if (/generated by the user while running local commands/i.test(t)) return true;
  return false;
}

/** Sessions whose FIRST prompt is a slash command (`/morning-digest`,
 *  `/news-digest`, a scheduled `claude -p "/x"` run) get a deterministic
 *  dated title — "morning-digest 2026-09-09" — instead of whatever
 *  summary Claude generates. One row per day, no hand-naming, and no
 *  collisions between weeks. Beats aiTitle; a saved name still wins. */
const BUILTIN_COMMANDS = new Set([
  'model', 'mcp', 'clear', 'help', 'config', 'compact', 'cost', 'status', 'login',
  'logout', 'resume', 'doctor', 'permissions', 'memory', 'agents', 'hooks', 'vim',
  'terminal-setup', 'release-notes', 'bug', 'feedback', 'export', 'context', 'tasks',
]);
export function slashCommandTitle(firstPromptText: string, tsMs: number): string {
  const text = firstPromptText || '';
  const m = /<command-name>\/?([\w][\w:.-]*)<\/command-name>/.exec(text);
  if (!m || !tsMs) return '';
  // Built-in CLI commands (/model, /mcp …) open a session but say nothing about
  // what it's for — they echo with <command-args>, skills don't. Leave those to
  // the normal ai-title path.
  if (BUILTIN_COMMANDS.has(m[1]) || /<command-args>/.test(text)) return '';
  const d = new Date(tsMs);
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${m[1]} ${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

function textFromContent(content: unknown): string {
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) {
    const t = content.find((x: any) => x && x.type === 'text' && typeof x.text === 'string');
    if (t) return (t as any).text;
  }
  return '';
}

function parseFile(path: string, mtimeMs: number): Session {
  const id = path.split('/').pop()!.replace(/\.jsonl$/, '');
  let cwd = '';
  let title = '';
  let lastPrompt = '';
  let gitBranch = '';
  let permissionMode = '';
  let messageCount = 0;
  let lastType = '';
  let firstUuid = '';
  let lastRole = ''; // role of the last user/assistant record (ignores metadata lines)
  let firstUserText = '';
  let lastActivityMs = 0; // newest conversational-record timestamp
  let lastUserMs = 0; // newest timestamp of a prompt I actually typed
  let firstActivityMs = 0; // oldest conversational-record timestamp
  let sawAiTitle = false;
  let slashTitle = '';
  let sawFirstPrompt = false; // any real user prompt seen yet (junk or not)

  let text = '';
  try {
    text = readFileSync(path, 'utf8');
  } catch {
    /* unreadable — return what we have */
  }

  for (const line of text.split('\n')) {
    if (!line.trim()) continue;
    let r: any;
    try {
      r = JSON.parse(line);
    } catch {
      continue;
    }
    if (r.type) lastType = r.type;
    if (r.type === 'user' || r.type === 'assistant') {
      lastRole = r.type;
      if (!firstUuid && typeof r.uuid === 'string') firstUuid = r.uuid;
      // Track the newest turn timestamp. Sub-agent (sidechain) turns count too —
      // they mean the session is actively working. Metadata records carry no
      // timestamp and so never bump this.
      if (typeof r.timestamp === 'string') {
        const t = Date.parse(r.timestamp);
        if (t > lastActivityMs) lastActivityMs = t;
        if (!firstActivityMs || t < firstActivityMs) firstActivityMs = t;
      }
    }
    if (!cwd && typeof r.cwd === 'string') cwd = r.cwd;
    if (typeof r.gitBranch === 'string') gitBranch = r.gitBranch;
    if (typeof r.messageCount === 'number' && r.messageCount > messageCount) {
      messageCount = r.messageCount;
    }
    if (r.type === 'ai-title' && r.aiTitle) {
      title = r.aiTitle;
      sawAiTitle = true;
    }
    if (r.type === 'last-prompt') lastPrompt = r.lastPrompt || r.content || lastPrompt;
    if (r.type === 'permission-mode' && r.permissionMode) permissionMode = r.permissionMode;
    if (r.type === 'user' && r.message && !r.isMeta && !r.isSidechain) {
      // A real prompt, not a tool result (textFromContent finds no 'text' block
      // in those), a slash-command echo, or a sub-agent's instructions.
      const t = textFromContent(r.message.content);
      if (t && !sawFirstPrompt) {
        sawFirstPrompt = true;
        slashTitle = slashCommandTitle(t, typeof r.timestamp === 'string' ? Date.parse(r.timestamp) : 0);
      }
      if (t && !isJunkText(t)) {
        if (!firstUserText) firstUserText = t;
        if (typeof r.timestamp === 'string') {
          const ts = Date.parse(r.timestamp);
          if (ts > lastUserMs) lastUserMs = ts;
        }
      }
    }
  }

  if (slashTitle) title = slashTitle;
  if (!title) {
    const cleanLast = lastPrompt && !isJunkText(lastPrompt) ? lastPrompt : '';
    title = truncate(firstUserText || cleanLast || '(untitled)', 60);
  }

  return {
    id,
    path,
    cwd: cwd || homedir(),
    title,
    lastPrompt: truncate(lastPrompt || firstUserText, 240),
    gitBranch,
    permissionMode,
    messageCount,
    mtimeMs,
    lastActivityMs: lastActivityMs || mtimeMs,
    lastUserMs,
    firstActivityMs,
    lastType,
    firstUuid,
    awaitingReply: lastRole === 'user',
    isStub: sawAiTitle && lastRole === '',
  };
}

/**
 * When a session last wanted my attention — the sidebar's sort key.
 *
 * Two things earn the top slot: a message I just sent, and a session going
 * quiet because it's now waiting on me. Work in flight earns nothing, so a
 * chatty background session can't churn its way above the one I'm actually
 * talking to; it re-surfaces the moment it finishes and needs an answer.
 *
 * Neither is sticky: both are timestamps, so typing into another session
 * simply gives that one a newer one, and whatever was waiting slides down
 * without ever having been pinned.
 */
export function attentionMs(s: Session | undefined, busy: boolean): number {
  if (!s) return 0;
  // Busy: only my last message counts — its own activity is just noise until
  // it stops. Fall back to when it started, so a session I've never typed in
  // (resumed from history, driven from elsewhere) still has a sane place.
  if (busy) return s.lastUserMs || s.firstActivityMs || s.lastActivityMs;
  // Idle / ready / dead: whichever came last — my message, or the moment it
  // fell quiet waiting for me.
  return Math.max(s.lastUserMs, s.lastActivityMs);
}

// Sidecar activity: Claude Code now writes sub-agent transcripts and workflow
// state NEXT TO the session file — <project>/<session-id>/subagents/…,
// including workflow agents nested at subagents/workflows/wf_*/agent-*.jsonl —
// instead of interleaving them in the main .jsonl. While a session waits on
// sub-agents its main transcript goes completely quiet, so the busy signal
// must fold these mtimes in or the row shows a false green "ready".
// tool-results/ is skipped — it's only written during main-transcript turns,
// which already bump the main file — as is workflows/scripts/ (write-once).
function newestFileMs(dir: string, depth: number): number {
  let max = 0;
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return 0; // no such sidecar — the common case
  }
  for (const e of entries) {
    const p = join(dir, e.name);
    if (e.isDirectory()) {
      if (depth > 0 && e.name !== 'scripts') max = Math.max(max, newestFileMs(p, depth - 1));
      continue;
    }
    try {
      const st = statSync(p);
      if (st.mtimeMs > max) max = st.mtimeMs;
    } catch {
      /* raced a delete — skip */
    }
  }
  return max;
}

function sidecarActivityMs(projectDir: string, id: string): number {
  return Math.max(
    newestFileMs(join(projectDir, id, 'subagents'), 2),
    newestFileMs(join(projectDir, id, 'workflows'), 1),
  );
}

export interface ForkView {
  /** one session per logical conversation — the newest fork — newest-first */
  sessions: Session[];
  /** every member id (ancestors AND the head itself) → the head session */
  canonical: Map<string, Session>;
}

/**
 * Collapse `--resume` forks: group transcripts by the conversation they belong
 * to (firstUuid — see Session.firstUuid) and keep only the most recently
 * written file of each group. Without this every reopen of a session leaves a
 * stale ancestor file behind that would render as a duplicate sidebar row.
 */
export function collapseForks(all: Session[]): ForkView {
  const groups = new Map<string, Session[]>();
  for (const s of all) {
    const key = s.firstUuid || s.id; // no turns yet → its own group
    const g = groups.get(key);
    if (g) g.push(s);
    else groups.set(key, [s]);
  }
  const sessions: Session[] = [];
  const canonical = new Map<string, Session>();
  for (const g of groups.values()) {
    const head = g.reduce((a, b) => (b.mtimeMs > a.mtimeMs ? b : a));
    // Resume stubs (see Session.isStub) can't be grouped with their parent —
    // no turns, no firstUuid — so hide them rather than show a duplicate row.
    // Once a message is sent in the fork the file gains the copied history and
    // collapses into its conversation normally. Still registered in canonical
    // so a pane that somehow references the stub id resolves to something.
    if (!head.isStub) sessions.push(head);
    for (const s of g) canonical.set(s.id, head);
  }
  sessions.sort((a, b) => b.mtimeMs - a.mtimeMs);
  return { sessions, canonical };
}

/**
 * May a brand-new orc pane (born at `bornMs`) adopt this transcript as its own?
 * Its own transcript can only have STARTED after the pane existed, so the first
 * conversational timestamp must be ≥ born. A transcript merely *modified* after
 * born is not enough — a claude running OUTSIDE orc in the same cwd (another
 * terminal/IDE) keeps bumping its transcript, and matching on mtime alone let a
 * new pane steal that session's identity. `bornMs === 0` (panes predating the
 * born field) and `firstActivityMs === 0` (no timestamped turns) fall back to
 * the permissive old behaviour.
 */
export function canAdopt(s: Session, bornMs: number): boolean {
  if (s.mtimeMs < bornMs) return false;
  if (!bornMs || !s.firstActivityMs) return true;
  return s.firstActivityMs >= bornMs;
}

/** Scan ~/.claude/projects for all sessions, newest-first. mtime-cached. */
export function scanSessions(): Session[] {
  const out: Session[] = [];
  if (!existsSync(PROJECTS_DIR)) return out;

  let projectDirs: string[] = [];
  try {
    projectDirs = readdirSync(PROJECTS_DIR);
  } catch {
    return out;
  }

  for (const pd of projectDirs) {
    const dir = join(PROJECTS_DIR, pd);
    let files: string[] = [];
    try {
      files = readdirSync(dir);
    } catch {
      continue;
    }
    for (const f of files) {
      if (!f.endsWith('.jsonl')) continue;
      const p = join(dir, f);
      let st;
      try {
        st = statSync(p);
      } catch {
        continue;
      }
      const cached = cache.get(p);
      let session: Session;
      if (cached && cached.mtimeMs === st.mtimeMs) {
        session = cached.session;
      } else {
        session = parseFile(p, st.mtimeMs);
        cache.set(p, { mtimeMs: st.mtimeMs, session });
      }
      // Fold sub-agent / workflow sidecar writes into the session's effective
      // freshness (the cache keeps the raw parse — keyed on the raw file
      // mtime — so derive a copy rather than mutating it).
      const sidecar = sidecarActivityMs(dir, session.id);
      if (sidecar > session.mtimeMs) {
        session = {
          ...session,
          mtimeMs: sidecar,
          lastActivityMs: Math.max(session.lastActivityMs, sidecar),
        };
      }
      out.push(session);
    }
  }

  out.sort((a, b) => b.mtimeMs - a.mtimeMs);
  return out;
}
